   ------------------------------------------------------------------------
   -- Copyright 2013 Expedia, Inc
   --
   -- Description:
   --   Table definition for DM.RPT_HEXDM_AGG_SEGMENT 
   --
   -- Change History:
   --   Date         Author         Description
   --   ----------   ----------     --------------------------------------
   --   2013-11-12   nsucheendran   Creation for jira - 94607
   -----------------------------------------------------------------------

CALL DBADM.SP_DROP_TABLE('DM','RPT_HEXDM_AGG_SEGMENT');
   
CREATE TABLE DM.RPT_HEXDM_AGG_SEGMENT 
(
		RPT_HEX_SEG_UUID				VARCHAR(100),
		SEGMENT_NUMBER 					SMALLINT,
		SEGMENT_NAME 					VARCHAR(100),
		EXPERIMENT_NAME 				VARCHAR(100),
		VARIANT_NAME    				VARCHAR(100),
		REPORT_START_DATE       		VARCHAR(100),
		REPORT_END_DATE 				VARCHAR(100),
		STATUS  						VARCHAR(100),
		REPORT_TRANSACTION_END_DATE     VARCHAR(100),
		TEST_MANAGER    				VARCHAR(100),
		PRODUCT_MANAGER 				VARCHAR(100),
		POD     						VARCHAR(100),
		EXPERIMENT_TEST_ID      		VARCHAR(100),
		LOCAL_DATE      				VARCHAR(100),
		NEW_VISITOR_IND 				VARCHAR(100),
		PAGE_ASSIGNED_ENTRY_PAGE_NAME   VARCHAR(300),
		SITE_SECTN_NAME 				VARCHAR(100),
		USER_CNTEXT_NAME        		VARCHAR(100),
		BROWSER_HEIGHT  				VARCHAR(100),
		BROWSER_WIDTH   				VARCHAR(100),
		MOBILE_IND      				VARCHAR(100),
		PLATFORM_TYPE   				VARCHAR(100),
		DAYS_UNTIL_STAY 				VARCHAR(100),
		LENGTH_OF_STAY 					VARCHAR(100) ,
		NUMBER_OF_ROOMS 				VARCHAR(100),
		NUMBER_OF_ADULTS_CHILDREN 		VARCHAR(100),
		CHILDREN_IN_SEARCH_FLAG			VARCHAR(100),
		ENTRY_PAGE_NAME 				VARCHAR(100),
		OPERATING_SYSTEM_NAME   		VARCHAR(100),
		BRWSR_NAME      				VARCHAR(100),
		BRWSR_TYP_NAME  				VARCHAR(100),
		PROPERTY_TYP_NAME       		VARCHAR(100),
		PROPERTY_PARNT_CHAIN_NAME       VARCHAR(100),
		PROPERTY_BRAND_NAME     		VARCHAR(100),
		PROPERTY_SUPER_REGN_NAME        VARCHAR(100),
		PROPERTY_REGN_ID        		INT,
		PROPERTY_REGN_NAME     			VARCHAR(100),
		PROPERTY_MKT_ID 				INT,
		PROPERTY_MKT_NAME       		VARCHAR(100),
		PROPERTY_SUB_MKT_ID     		INT,
		PROPERTY_SUB_MKT_NAME   		VARCHAR(100),
		PROPERTY_CNTRY_NAME     		VARCHAR(100),
		PROPERTY_STATE_PROVNC_NAME      VARCHAR(100),
		PROPERTY_CITY_NAME      		VARCHAR(100),
		EXPE_HALF_STAR_RTG      		VARCHAR(100),
		PROPERTY_PARNT_CHAIN_ACCT_TYP_NAME      VARCHAR(100),
		PROPERTY_PAYMNT_CHOICE_ENABL_IND        VARCHAR(100),
		PROPERTY_CNTRCT_MODEL_NAME      VARCHAR(100),
		POSA_SUPER_REGION       		VARCHAR(100),
		POSA_REGION     				VARCHAR(100),
		POSA_COUNTRY    				VARCHAR(100),
		MKTG_CHNNL_NAME 				VARCHAR(100),
		MKTG_SUB_CHNNL_NAME     		VARCHAR(100),
		MKTG_CHNNL_NAME_DIRECT  		VARCHAR(100),
		MKTG_SUB_CHNNL_NAME_DIRECT      VARCHAR(100),
		HCOM_SRCH_DEST_TYP_NAME 		VARCHAR(100),
		HCOM_SRCH_DEST_NAME     		VARCHAR(100),
		HCOM_SRCH_DEST_CNTRY_NAME       VARCHAR(100),
		HCOM_SRCH_DEST_ID       		VARCHAR(100),
		PSG_MKT_NAME    				VARCHAR(100),
		PSG_MKT_REGN_NAME       		VARCHAR(100),
		PSG_MKT_SUPER_REGN_NAME 		VARCHAR(100),
		DOM_INTL_FLAG   				VARCHAR(100),
		NUM_UNIQUE_VIEWERS      		BIGINT,
		NUM_UNIQUE_PURCHASERS   		BIGINT,
		NUM_UNIQUE_CANCELLERS   		BIGINT,
		NUM_ACTIVE_PURCHASERS   		BIGINT,
		NUM_INACTIVE_PURCHASERS    		BIGINT,
		TOTAL_CANCELLATIONS     		BIGINT,
		NET_ORDERS      				BIGINT,
		NET_BKG_GBV     				DOUBLE,
		NET_BKG_ROOM_NIGHTS     		BIGINT,
		NET_OMNITURE_GBV        		DOUBLE,
		NET_OMNITURE_ROOM_NIGHTS        BIGINT,
		NET_GROSS_PROFIT        		DOUBLE,
		NUM_REPEAT_PURCHASERS   		BIGINT,
		EXPERIMENT_CODE 				VARCHAR(100),
		VERSION_NUMBER  				SMALLINT,
		VARIANT_CODE    				VARCHAR(100)
		) 
    IN TS_PDPG_DM_HEX
    DISTRIBUTE BY HASH ( RPT_HEX_SEG_UUID ) 
	COMPRESS YES;

call sysproc.admin_cmd('RUNSTATS ON TABLE DM.RPT_HEXDM_AGG_SEGMENT ON KEY COLUMNS AND INDEXES ALL TABLESAMPLE SYSTEM(20) SET PROFILE ONLY'); 

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DM.RPT_HEXDM_AGG_SEGMENT TO ROLE ORDMRW;
GRANT SELECT on DM.RPT_HEXDM_AGG_SEGMENT to ROLE ORDMR;


