 ------------------------------------------------------------------------
   -- Copyright 2013 Expedia, Inc
   --
   -- Description:
   --   Table definition for DM.HEX_REPORTING_REQUIREMENTS 
   --
   -- Change History:
   --   Date         Author         Description
   --   ----------   ----------     ------------------------------------
   --   2013-11-12   nsucheendran   Creation for jira - 94607
   --   2014-01-14   agurumurthi    Creation for jira - 95015
 -----------------------------------------------------------------------

CALL DBADM.SP_DROP_TABLE('STGLDR','HEX_REPORTING_REQUIREMENTS');

CREATE TABLE STGLDR.HEX_REPORTING_REQUIREMENTS 
 (
	 EXPERIMENT_CODE	VARCHAR(100)	
	,EXPERIMENT_NAME	VARCHAR(200)	
	,VARIANT_CODE		VARCHAR(100)	
	,VARIANT_NAME		VARCHAR(200)	
	,VERSION_NUMBER		SMALLINT	
	,REPORT_START_DATE	DATE
	,REPORT_END_DATE	VARCHAR(100)
	,STATUS				VARCHAR(50)	
	,TRANS_DATE			VARCHAR(100)	
	,TEST_MANAGER		VARCHAR(100)	
	,PRODUCT_MANAGER	VARCHAR(100)	
	,POD				VARCHAR(100)	
	,EXPERIMENT_TEST_ID	VARCHAR(100)	
	,LAST_UPDATED_DT	TIMESTAMP
	,INSERT_DT			TIMESTAMP
 )
 IN TS_STAGE00
 COMPRESS YES;
 
  CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE STGLDR.HEX_REPORTING_REQUIREMENTS ON ALL COLUMNS AND INDEXES ALL SET PROFILE ONLY');
  
  GRANT DELETE,INSERT,SELECT,UPDATE ON STGLDR.HEX_REPORTING_REQUIREMENTS TO ROLE ORDMRW;
  GRANT SELECT on STGLDR.HEX_REPORTING_REQUIREMENTS to ROLE ORDMRW;
  GRANT DELETE,INSERT,SELECT,UPDATE ON STGLDR.HEX_REPORTING_REQUIREMENTS TO ROLE ORETLR;
  GRANT SELECT on STGLDR.HEX_REPORTING_REQUIREMENTS to ROLE ORETLR;
  